name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build and Publish WebAPI
        run: dotnet publish Peach.Host/Peach.Host.csproj --configuration Release --output ./publish/webapi --self-contained true --runtime linux-x64

      - name: Build and Publish WPFApp
        run: dotnet publish RuleTest/RuleTest.csproj --configuration Release --output ./publish/wpf --runtime win-x64 --self-contained true
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PEACHTOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.event.repository.name }}  ${{ steps.branch-name.outputs.current_branch }} v${{ github.run_number }}.${{ github.run_attempt }}
          draft: false
          prerelease: false

      - name: Upload WebAPI Release Asset
        id: upload_webapi_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PEACHTOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/webapi/Peach.Host.zip
          asset_name: Peach.Host.zip
          asset_content_type: application/zip

      - name: Upload WPF Release Asset
        id: upload_wpf_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PEACHTOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/wpf/RuleTest.zip
          asset_name: RuleTest.zip
          asset_content_type: application/zip